version: '3.8'

networks:
  xyz-network:
    driver: bridge


x-base-service: &base-service
  build:
    context: .
  stdin_open: true
  tty: true
  env_file: .env
  restart: on-failure
  depends_on:
    - redis
  networks:
    - xyz-network
  logging:
    driver: "json-file"
    options:
      max-size: "100m"

services:
# Caching service (Redis)
  redis:
    image: "redis:7.2-rc1-alpine"
    container_name: cache-service
    restart: always
    ports:
      - "6379:6379"
    command: redis-server
    volumes:
      - ./data/redis:/data
    networks:
      - xyz-network

  app:
    <<: *base-service
    container_name: rate-limiter-service
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./src:/srv/app/src
    healthcheck:
        test: [ "CMD", "curl", "http://localhost:${PORT}" ]
        interval: 30s
        timeout: 10s
        retries: 5
